# path to sdk scenarios
run: "custom" # (zenodo|custom)
scenario:
  zenodo: config/SDK_zenodo.csv
  custom: config/SDK_custom.csv

# solver 
solver: cplex # (cbc|cplex|gurobi)

# osemosys setup 
model: "resources/osemosys_pp.txt"
otoole: "resources/otoole.yaml"

# emission abatement config
emission_abatement:
  config: "config/emission_curves.csv"
  base_year: 2050
  reduction_method: "linear" # (linear|exp)
  include_backstop: False

# minfin data to extract
# NOTE: these names must match names in 'format_data.py' module!
minfin_files:
  - PWR_CapitalInvestment
  - MIN_AnnualVariableOperatingCost
  - PWR_AnnualVariableOperatingCost
  - PWR_AnnualFixedOperatingCost
  - PWR_ProductionByTechnologyAnnual